/* Class:       {{ api_name }}
 * Created On:  
 * Created by:  J. Pipkin (OpFocus, Inc)
 * Description: 
 */

@isTest
public class {{ api_name }} {
 
    @testSetup static void buildData(){
        
    }
 
    //test methods
 
    //static testMethod void myTest1() {
       
    //    Test.startTest();

    //    {{ batch_class }}.manual();

    //    Test.stopTest();
   
    //}
   
 
    //static testMethod void scheduleBatch() {
    //    {{ batch_class }}.schedule();
    //}
}